url: https://samazgor.github.io
baseurl: /

# Site settings
title: Github Page of Sam Azgor
email: sam@azgor.com
description: "Coding Away with GitHub"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/samazgor
  - title: facebook
    url: https://facebook.com/samazgor
  - title: google-plus
    url: https://profiles.google.com/114615829129728746591
  - title: instagram 
    url: http://instagram/samazgor
  - title: github
    url: http://github.com/samazgor
  - title: linkedin
    url: http://bd.linkedin.com/in/samazgor

# Postal address (add as many lines as necessary)
address:
  - line: Peace Park, Ainusbag
  - line: Dakkhinkhan, Dhaka-1230

# Build settings
markdown: kramdown
permalink: pretty
