# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam Azgor
email: sam@azgor.com
description: Webmaster and Sysadmin
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sam.azgor.com" # the base hostname & protocol for your site
paginate:	7 # The number of posts to show per page on your homepage

name: 'Sam Azgor'
bio: >
  Howdy. My name is Sam Azgor. My online presence started as a blogger. Currently i play with remote machines. Occasionally I write various type of articles.
author_image: "/assets/images/author.jpg"
twitter_username: samazgor
github_username:  samazgor

# Google Analytics
analytics_id: "UA-56619929-2"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
